import re
import unittest
from pathlib import Path

from animemachine.catalog.service import requires_admin


ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parents[1]
STATIC = PROJECT / "src" / "animemachine" / "web" / "static"


class WebContractTests(unittest.TestCase):
    def test_three_language_dictionary_keys_are_identical(self):
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        starts = {
            "zh-Hans": script.index('  "zh-Hans": {'),
            "en": script.index("  en: {"),
            "ja": script.index("  ja: {"),
        }
        content_starts = {language: script.index("\n", offset) + 1 for language, offset in starts.items()}
        blocks = {
            "zh-Hans": script[content_starts["zh-Hans"]:starts["en"]],
            "en": script[content_starts["en"]:starts["ja"]],
            "ja": script[content_starts["ja"]:script.index("\n};", starts["ja"])],
        }
        key_pattern = re.compile(r"(?:^|,)\s*([A-Za-z_][A-Za-z0-9_]*):", re.MULTILINE)
        keys = {language: set(key_pattern.findall(block)) for language, block in blocks.items()}
        self.assertEqual(keys["zh-Hans"], keys["en"])
        self.assertEqual(keys["zh-Hans"], keys["ja"])


    def test_capability_policy_blocks_admin_side_effects_before_execution(self):
        for path in (
            "/api/catalog/reshuffle", "/api/archive/update", "/api/archive/import",
            "/api/metadata/repair", "/api/library/audit", "/api/history/1/restore",
            "/api/connections/qbittorrent/credential", "/api/connections/ani-rss/credential",
            "/api/connections/subtitles/credentials", "/api/settings",
            "/api/auth/users", "/api/auth/users/7", "/api/diagnostics/network/recheck", "/api/images/preload/control",
            "/api/update/apply",
        ):
            self.assertTrue(requires_admin("POST", path), path)
        for method, path in (("PUT", "/api/config"), ("GET", "/api/logs"), ("GET", "/api/history"), ("GET", "/api/auth/users"),
                             ("GET", "/api/diagnostics/network"), ("GET", "/api/diagnostics/playback"), ("GET", "/api/images/preload"),
                             ("GET", "/api/system/health"), ("GET", "/api/update/status")):
            self.assertTrue(requires_admin(method, path), path)
        for path in ("/api/anime", "/api/anime/1/image/refresh", "/api/plans/" + "a" * 32 + "/submit"):
            self.assertFalse(requires_admin("POST", path), path)

    def test_update_details_and_seeded_random_ui_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        for value in (
            'data-tab="updates"', 'id="updateCurrentVersion"', 'id="updateLatestVersion"',
            'id="updateDownloadSource"', 'id="updateSha256Status"', 'id="updateUpgradeResult"',
            'id="automaticUpdateEnabled"', 'id="automaticUpdateMode"', 'id="automaticUpdateTime"',
            'id="updateSourceDiagnostics"',
        ):
            self.assertIn(value, html)
        self.assertIn('value="04:35"', html)
        self.assertIn('$("automaticUpdateMode").value = automaticUpdate.mode || "notify"', script)
        self.assertIn('$("automaticUpdateTime").value = automaticUpdate.time || "04:35"', script)
        self.assertNotIn("Math.random", script)
        self.assertIn('`${seed}:${value}`', script)
        self.assertIn('seed = String(stats.instance_random_seed || "anm")', script)
        self.assertIn('$("reshuffle").hidden = !random || authSession?.role !== "admin"', script)

    def test_release_https_and_offline_archive_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        dockerfile = (PROJECT / "packaging" / "docker" / "Dockerfile").read_text(encoding="utf-8")
        release = (PROJECT / "scripts" / "windows" / "Build-Release.ps1").read_text(encoding="utf-8")
        self.assertNotIn("Path]::GetRelativePath", release)
        tls = (PROJECT / "src" / "animemachine" / "network" / "tls.py").read_text(encoding="utf-8")
        requirements = (PROJECT / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn('id="importArchive"', html)
        self.assertIn('id="archiveFile"', html)
        self.assertIn('data-panel="diagnostics"', html)
        self.assertIn('id="recheckNetwork"', html)
        self.assertIn('id="imagePreloadStages"', html)
        self.assertIn('id="imagePreloadMeta"', html)
        self.assertIn('id="systemHealthSummary"', html)
        self.assertIn('id="systemHealthDiagnostics"', html)
        self.assertIn('id="catalogReadyBadge"', html)
        self.assertIn('id="playbackDiagnostics"', html)
        self.assertIn('/api/archive/import', script)
        self.assertIn('/api/startup/state', script)
        self.assertIn('/api/diagnostics/network/recheck', script)
        self.assertIn('/api/images/preload/control', script)
        self.assertIn('/api/system/health', script)
        self.assertIn('/api/diagnostics/performance', script)
        self.assertIn('performanceBaseline', script)
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".toolbar button,", styles)
        self.assertIn("white-space: nowrap", styles)
        self.assertIn("min-height: 104px", styles)
        self.assertIn("Promise.allSettled", script)
        self.assertIn('networkProfile', script)
        self.assertIn('function diagnosticTrendSparkline', script)
        self.assertIn('windows_system_proxy', script)
        self.assertIn('estimatedRemaining', script)
        self.assertIn('certifi==', requirements)
        self.assertIn('truststore==', requirements)
        self.assertIn('pip install', release)
        self.assertIn('ca-certificates', dockerfile)
        self.assertIn('ANM_CA_BUNDLE', tls)
        self.assertNotIn("player bridge", script.casefold())

    def test_auth_filter_memory_grouped_sources_and_playback_selection(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        for element_id in ("loginDialog", "loginForm", "authButton", "submissionAllowed", "userList"):
            self.assertIn(f'id="{element_id}"', html)
        self.assertIn('data-admin-only', html)
        self.assertIn('const filterStorageKey = "anm-catalog-filters-v1"', script)
        self.assertIn("function restoreFilterState()", script)
        self.assertIn("torrentGroups = (rows)", script)
        self.assertIn("sequence.isdisjoint", (PROJECT / "src" / "animemachine" / "torrents" / "runtime.py").read_text(encoding="utf-8"))
        self.assertIn('playbackSources.get(animeId)', script)
        self.assertIn("Continue with the selection-based fallback", script)
        self.assertNotIn("Player-Bridge", script)
        self.assertIn('class="user-row"', script)
        self.assertIn('id="userManagementStatus"', html)
        self.assertIn('id="applyApplicationUpdateDetail"', html)
        self.assertIn('id="checkApplicationUpdateDetail"', html)
        self.assertNotIn('id="applyApplicationUpdate"', html)
        self.assertNotIn('id="checkApplicationUpdate"', html)
        self.assertNotIn('id="appVersion"', html)
        self.assertNotIn('id="updateNotice"', html)
        self.assertNotIn('id="updateStatus"', html)
        self.assertIn('/api/update/status', script)
        self.assertIn('/api/update/apply', script)
        self.assertIn('function playbackHtml(state)', script)
        self.assertNotIn('&& !localMediaAvailable && !capabilities.qbtCredentialConfigured', script)
        self.assertNotIn('aniRssPathUnavailable', script)
        self.assertNotIn('aniRssPathUnconfigured', script)
        self.assertNotIn('data-player=\"potplayer\"${disabledDirect}', script)
        self.assertIn('playbackHtml(playbackState)', script)
        self.assertNotIn('data-i18n="acceptedContentHint"', html)

    def test_three_language_static_and_relation_title_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        for key in ("catalogTagline", "languageControl", "closeDialog", "sortDirectionLabel", "settingsSectionsLabel"):
            self.assertEqual(3, script.count(f"{key}:"), key)
        for attribute in ("data-i18n-aria-label", "data-i18n-title"):
            self.assertIn(attribute, html)
        self.assertIn('querySelectorAll("[data-i18n-aria-label]")', script)
        self.assertIn('querySelectorAll("[data-i18n-title]")', script)
        self.assertIn("y.related_display_title || y.related_title", script)
        self.assertNotIn("AnimeMachine · Automated Anime Library", html)
        self.assertNotIn("AnimeMachine · Automated Anime Library", script)

    def test_settings_and_filters_are_product_features(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        for element_id in ("archiveGroups", "serialGroupsZh", "serialGroupsEn", "serialGroupsJa",
                           "serialSubtitleLanguage", "otherGroupsEnabled", "allowedResolutions", "torrentPoolPath",
                           "qbtEndpoint", "logList", "watchList", "directorSuggestions", "voiceSuggestions",
                           "relationDialog", "relationGraph", "series_member"):
            self.assertIn(f'id="{element_id}"', html)
        for element_id in ("repairMetadata", "externalReadOnlyEnabled", "externalReadOnlyKind", "externalReadOnlyPath"):
            self.assertIn(f'id="{element_id}"', html)
        self.assertNotIn("prowlarrEndpoint", html)
        self.assertNotIn("testProwlarr", script)
        self.assertIn('data-tab="groups"', html)
        self.assertIn('data-tab="priority"', html)
        self.assertNotIn('id="priorityColumns"', html)
        self.assertIn('class="priority-tree"', html)
        self.assertIn('["\u6807\u6e05", "Standard definition", "\u6a19\u6e96\u753b\u8cea"]', script)
        self.assertIn('api("/api/resource-groups",', script)
        self.assertIn("const archiveIds = new Set(p.archiveGroupIds", script)
        self.assertIn("p.resourceGroups.filter((x) => archiveIds.has(x.id))", script)
        self.assertNotIn("serialCatalog.flatMap", script)
        self.assertNotIn('<section class="about-product" aria-labelledby="aboutTitle">', html)
        self.assertNotIn("ABOUT ANIMEMACHINE", html)
        self.assertLess(html.index('data-tab="logs"'), html.index('data-tab="about"'))
        self.assertIn('catalog: "AnimeMachine"', script)
        self.assertIn('aboutTitle: "About AnimeMachine"', script)
        self.assertNotIn('catalog: "全自動アニメライブラリ"', script)
        self.assertNotIn("真实关联本地资源池与收藏库状态的全量动画数据库", script)
        self.assertNotIn("离线归档构建，可追溯、可筛选、可持续更新。", html)
        self.assertIn('src="/boot.js"', html)
        boot = (STATIC / "boot.js").read_text(encoding="utf-8")
        self.assertIn("navigator.languages || [navigator.language]", boot)
        self.assertIn('const saved = localStorage.getItem("anm-language")', boot)
        self.assertIn("if (supported.has(saved)) language = saved", boot)
        self.assertIn("detectSystemLanguage", script)
        self.assertIn("storedLanguage() || detectSystemLanguage(c.ui?.availableLanguages)", script)
        self.assertIn('data-i18n="loadingWorks"', html)
        self.assertIn('loadingWorks: "Loading works, please wait..."', script)
        self.assertNotIn("制作 ·", script)
        self.assertIn('id="season"', html)
        self.assertNotIn('id="country"', html)
        for value in ("local", "external", "submitted", "not_in_library"):
            self.assertIn(f'value="{value}" checked', html)
        self.assertNotIn('value="occupied_review"', html)
        self.assertIn('localLibrary: "本地入库"', script)
        self.assertIn('externalReadOnly: "外部只读"', script)
        self.assertIn('submittedDownload: "提交下载"', script)
        self.assertIn('notInLibrary: "暂未入库"', script)
        self.assertEqual(3, script.count("notInLibrary:"))
        self.assertNotIn('notInLibrary: "未登记"', script)
        self.assertNotIn('notInLibrary: "Not registered"', script)
        self.assertNotIn('notInLibrary: "未登録"', script)
        self.assertIn('"local",\n      "external",\n      "submitted",\n      "not_in_library"', script)
        self.assertLess(html.index('id="season"'), html.index('id="studio"'))
        self.assertLess(html.index('id="studio"'), html.index('id="media_type"'))
        self.assertNotIn('config.ui?.filterDefaults?.country || "JP"', script)
        self.assertIn('id="viewToggle"', html)
        self.assertNotIn('id="cardsView"', html)
        self.assertNotIn('id="tableView"', html)
        self.assertIn('aniRssManaged: "Ani-RSS 媒体已存在"', script)
        self.assertIn('aniRssResources: "Ani-RSS 资源可用"', script)
        self.assertIn('if (season === "winter") return { from: `${y - 1}-12`, to: `${y}-02` };', script)
        self.assertIn('select.disabled = !enabled', script)
        self.assertIn('if (b.dataset.tab === "updates") loadApplicationUpdate();', script)
        self.assertNotIn('b.dataset.tab === "updates" || b.dataset.tab === "about"', script)
        self.assertIn('padding: 7px 12px', (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn('preloadWaitingNetwork: "已进入本地模式；网络恢复后将自动继续后台预加载。"', script)
        self.assertIn('payload?.state === "waiting_network" ? t("preloadWaitingNetwork")', script)
        self.assertLess(html.index('id="catalogReadyBadge"'), html.index('id="buildInfo"'))
        self.assertIn('["__other__", allow.resolution !== false]', script)
        self.assertIn('movie: ["剧场版 / 电影", "Theatrical / film", "劇場版 / 映画"]', script)
        self.assertIn('light_novel: ["轻小说改"', script)
        self.assertIn('novel: ["小说改"', script)
        self.assertIn('time_travel: ["穿越", "Time travel", "タイムトラベル"]', script)
        self.assertIn('galgame: ["Galgame", "Galgame", "美少女ゲーム"]', script)
        self.assertIn('yuri: ["百合", "Yuri", "百合"]', script)
        self.assertIn('magical_girl: ["魔法少女", "Magical girl", "魔法少女"]', script)
        self.assertIn('harem: ["后宫", "Harem", "ハーレム"]', script)
        self.assertIn('children: ["儿童向", "Children", "子供向け"]', script)
        self.assertIn('avant_garde: ["非常规表达", "Unconventional expression", "非定型表現"]', script)
        self.assertNotIn('shounen: [', script)
        self.assertNotIn('seinen: [', script)
        self.assertNotIn('shoujo: [', script)
        self.assertNotIn('drama: [', script)
        self.assertIn('same_setting: ["", "", ""]', script)
        self.assertIn('sameAsOriginalLanguage(x)', script)
        self.assertIn('Number(catalogStats.runtime?.torrents || 0) === 0', script)
        self.assertIn('class="status-row"', html)
        self.assertNotIn('class="build-row"', html)
        self.assertLess(html.index('id="catalogReadyBadge"'), html.index('id="scanProgressText"'))
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        self.assertIn('grid-template-rows: auto auto', styles)
        self.assertIn('overflow-x: auto', styles)
        self.assertIn('id="scanProgress"', html)
        self.assertIn('searchPoolNow: "重新搜索本地资源"', script)
        self.assertIn('searchAniRss: "通过 Ani-RSS 查询资源"', script)
        self.assertIn('id="aniRssMode"', html)
        self.assertIn('verifyWork: "立即核验"', script)
        self.assertNotIn('id="minimumDate"', html)
        self.assertNotIn('id="refreshImage"', script)
        self.assertIn('availability: "可用来源"', script)
        self.assertIn('externalMediaAvailable: "外部媒体已映射"', script)
        self.assertIn('external: "外部来源（只读）"', script)
        self.assertIn('sourceType: "类型"', script)
        self.assertIn('originalName: "原作名称"', script)
        self.assertIn('originalAuthor: "作者"', script)
        self.assertIn('seriesComposition: "系列构成"', script)
        self.assertIn('characterDesign: "角色设计"', script)
        self.assertIn('music: "音乐"', script)
        self.assertIn('excludedSerialProfile: "语言不符"', script)
        self.assertIn('excludedResolution: "分辨率不符"', script)
        self.assertIn('factHtml("original-name-fact"', script)
        self.assertIn('factHtml("tags-fact"', script)
        self.assertIn('label("theme", code)', script)
        self.assertIn('storageDirectories = [...new Set(group.members.map((item) => item.storageDirectory)', script)
        self.assertNotIn('${esc(group.sample.name)}', script)
        self.assertIn('<b>Ani-RSS</b>', script)
        self.assertIn('resourceResolutionText = (value, scan = "p")', script)
        self.assertIn('["unknown", "other", "null", "0"].includes(lower)', script)
        self.assertIn('resourceResolutionText(y.resolution, y.scan)', script)
        self.assertIn('resourceResolutionText(y.resolution)', script)
        self.assertIn('stateOther: "状态待确认"', script)
        self.assertNotIn('unavailable: "暂无资源"', script)
        self.assertIn('library_state || "not_in_library"', script)
        self.assertIn('class="completion unassessed"', script)
        self.assertIn('originalWithKind: "原作·{kind}"', script)
        self.assertIn('adaptationWithKind: "改编·{kind}"', script)
        self.assertIn('id="relationSubjectPopover"', html)
        self.assertIn("function relationSubjectChips(node)", script)
        self.assertIn("function showRelationSubjectPopover", script)
        self.assertIn("return preferred(node) || node.title_ja", script)
        self.assertIn("function relationMonth(v)", script)
        self.assertIn('month: "short"', script)
        self.assertIn('graphTitle(nodesById.get(graph.rootAnimeId)) || graph.seriesTitle', script)
        self.assertIn('class="relation-node-foot"', script)
        self.assertIn(".relation-subject-popover", (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn('y.relation_code !== "other"', script)
        self.assertIn('href="https://bgm.tv/subject/${Number(y.related_bgm_id)}"', script)
        self.assertIn('id="detailRelations"', script)
        self.assertIn("localizedSummary(x)", script)
        self.assertIn("x.title_ja_localized || x.title_ja", script)
        self.assertIn("x.title_zh_hans || x.title_zh_hans_localized || x.title_ja", script)
        self.assertIn("englishReadableTitle(x.title_en)", script)
        self.assertIn("englishReadableTitle(x.title_en_localized)", script)
        self.assertNotIn("englishReadableTitle(x.title_ja)", script)
        self.assertIn("englishReadableTitle(x.title_en_localized) || x.title_ja", script)
        self.assertNotIn("missingEnglishTitle", script)
        self.assertIn('data-i18n="${id === "era" ? "custom" : "all"}"', script)
        self.assertIn("${esc(graphTitle(node))}", script)
        self.assertIn('["合集", "Collection", "コレクション"]', script)
        self.assertIn('return "ko"', script)
        self.assertIn('return "ru"', script)
        self.assertIn('t("externalSource")} · ${t("readOnlyMapping")}', script)
        unavailable = html.index('value="unavailable"')
        self.assertNotIn("checked", html[unavailable:unavailable + 80])
        self.assertIn("showRelationGraph", script)
        self.assertIn('id="reshuffle"', html)
        self.assertNotIn("\u78c1\u8d34", html + script)
        self.assertIn('cards: "卡片"', script)
        self.assertLess(html.index('id="reshuffle"'), html.index('id="sort"'))
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".inline {", styles)
        self.assertIn("display: inline-flex", styles)
        self.assertIn("padding: 10px 14px", styles)
        self.assertIn('relationDialog.classList.toggle("expanded")', script)
        self.assertIn('relatedWorksCount: "系列内作品数：{count}"', script)
        self.assertIn('data-relation-toggle=', script)
        self.assertIn('data-relation-export="png"', script)
        self.assertIn('data-relation-export="svg"', script)
        self.assertIn("global_search_only", script)
        self.assertIn("layoutRelationLabels", script)
        self.assertIn("relationGraphBounds", script)
        self.assertIn("safePadding = 28", script)
        self.assertIn('transform="translate(${shiftX} ${shiftY})"', script)
        self.assertIn("labelOverlap * 2000", script)
        self.assertIn("relationTrackCodes", script)
        self.assertIn("routeRelationEdge", script)
        self.assertIn('sequel: { offset: 0, side: 0 }', script)
        self.assertIn("if (!obstacle && sourceY === targetY", script)
        self.assertIn("assignRelationPorts", script)
        self.assertIn("centerPortPriority", script)
        self.assertIn('edge.relation_code === "sequel" && chronologyCorrect', script)
        self.assertIn("Number(!sameRow) * 10 + relationRank", script)
        self.assertIn("relationLaneCapacity", script)
        self.assertIn("route.local", script)
        self.assertIn("routedRelationMetadata", script)
        self.assertIn("routedTotal - routedLane - 1", script)
        self.assertIn("corridorRank * corridorLaneSpacing", script)
        self.assertNotIn("`outer:${style.side}:${edge.target_anime_id}`", script)
        self.assertIn("assignRelationPorts(orderedEdges, positions, nodesById)", script)
        self.assertIn("distribute(negative, -38, 0, 0)", script)
        self.assertIn("verticalCorridorClear", script)
        self.assertIn("Math.abs(sourceCenterX - targetCenterX) <= 24", script)
        self.assertIn("verticalGapBottom - verticalGapTop >= 12", script)
        self.assertIn("direct: !collisionNudge,\n      vertical: true", script)
        self.assertIn("route.direct && !route.vertical", script)
        self.assertIn('prequel: ["前传", "Prequel", "前日譚"]', script)
        self.assertIn('prequel: { offset: 0, side: 0 }', script)
        self.assertIn("verticalGroups", script)
        self.assertIn("laneXSpacing", script)
        self.assertIn("laneYSpacing", script)
        self.assertIn("corridorLaneSpacing", script)
        self.assertIn("targetId: edge.target_anime_id", script)
        self.assertIn("other.targetId === item.targetId", script)
        self.assertIn("other.horizontals.some", script)
        self.assertIn("relationSegmentConflictCost", script)
        self.assertIn("createRelationSegmentIndex", script)
        self.assertIn("cellSize = 96", script)
        self.assertIn("segmentIndex.conflictScore", script)
        self.assertIn("collisionNudge", script)
        self.assertIn("baseCenteredLane", script)
        self.assertIn("candidateCenteredLane", script)
        self.assertIn('data-source="${edge.source_anime_id}"', script)
        self.assertIn('data-target="${edge.target_anime_id}"', script)
        self.assertIn("refineRelationRouting", script)
        self.assertIn("!verticalCorridorClear", script)
        self.assertIn("preferredSide", script)
        self.assertIn("bypass: true", script)
        self.assertIn("Number(right.bypass) - Number(left.bypass)", script)
        self.assertIn("const center = (group.length - 1) / 2", script)
        self.assertIn("const outerGroups = []", script)
        self.assertIn("other.side === item.side", script)
        self.assertIn("outerGroups.forEach", script)
        self.assertIn("String(aTarget?.start_month).localeCompare", script)
        self.assertIn("sourceTurnRank", script)
        self.assertIn("sourceTurnTotal - sourceTurnRank - 1", script)
        self.assertIn("sourceFans", script)
        self.assertIn("routeObstacleCount", script)
        self.assertIn("!edge.grouping && (sourceAbove || sourceBelow)", script)
        self.assertIn("contextRoute: true", script)
        self.assertIn("diagonal: true", script)
        self.assertIn("route.targetSegment", script)
        self.assertIn("contextGroups", script)
        self.assertIn("Gray cross-series connectors", script)
        self.assertIn("relationPathSegments", script)
        self.assertIn("foreignLineOverlap", script)
        self.assertIn("灰色的虚框节点是相关联的不同系列作品", script)
        self.assertIn("Gray dashed nodes are related works from other series", script)
        self.assertIn("灰色の破線枠ノードは、関連する別シリーズの作品です", script)
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        self.assertIn("height: min(780px, 88vh)", styles)
        self.assertIn("scrollbar-gutter: stable both-edges", styles)
        self.assertIn("protectedTargets.has(edge.target_anime_id)", script)
        self.assertIn(".relation-edge-label", (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn('not_in_library_catalog: "未加入本地库"', script)
        self.assertIn('graphUnavailableSelect: "当前没有可提交的合格资源"', script)
        self.assertIn("canSelect = node.selectable", script)
        self.assertIn('canSelect ? "" : "disabled"', script)
        self.assertNotIn("relation-node-dot", script)
        self.assertIn("terminalLead = 34 + routedLane * 8", script)
        self.assertIn("contextGap =", script)
        self.assertIn('background-position: center 33%', (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn("stage_replace", script)
        self.assertIn("graphExistingWarning", script)
        self.assertIn('pageSize = "12"', script)
        self.assertIn('<option value="20">20</option>', html)
        self.assertIn('seriesWork: "系列作品"', script)
        self.assertIn('seriesWork: "Series work"', script)
        self.assertIn('seriesWork: "シリーズ作品"', script)
        self.assertIn("coverObserver?.disconnect()", script)
        self.assertIn("batch.active < 12", script)
        self.assertIn("searchController?.abort()", script)
        self.assertIn("cancelCoverLoads();", script)
        self.assertIn('{ rootMargin: "240px 0px 240px 0px" }', script)
        self.assertIn("predictiveCoverWindow", script)
        self.assertIn("18 - batch.active - batch.queue.length", script)
        self.assertIn("function showModalDialog(dialog)", script)
        self.assertIn("function modalWheelHasTarget(event, dialog)", script)
        self.assertIn("function scrollModalFallback(event, dialog)", script)
        self.assertIn('document.addEventListener("wheel"', script)
        self.assertIn('if (modal && !modal.contains(target))', script)
        self.assertIn("dialog::backdrop {\n  background: rgba(11, 25, 20, 0.65);\n}", styles)
        self.assertIn("sameMediaMainlineLinks", script)
        self.assertIn("explicitGraphSequenceNumber", script)
        self.assertIn("relaxCrossingBranchTargets", script)
        self.assertIn("candidates = [28, -28, 56, -56]", script)
        self.assertIn("detour * 1.6", script)
        self.assertIn("mediaOrder.length + index", script)
        self.assertNotIn("personHint", script)
        self.assertNotIn('data-i18n="personHint"', html)
        self.assertIn("margin: 18px auto 60px", styles)
        self.assertIn('searchPlaceholder: "中文、英文、日语或简称"', script)
        self.assertIn('searchPlaceholder: "English, Japanese, Chinese or abbreviation"', script)
        self.assertIn('searchPlaceholder: "日本語・英語・中国語・略称"', script)
        self.assertIn('\\p{Script=Latin}', script)
        self.assertIn('/api/watches?language=${encodeURIComponent(language)}', script)
        self.assertIn('preferred(current) || current.title', script)
        self.assertIn("endMonth - 1 - 5", script)
        self.assertIn('$("start_to").value = monthValue(endYear, endMonth)', script)
        self.assertIn("function localizeStaticUi()", script)
        self.assertLess(script.rindex("localizeStaticUi();"), script.rindex("initialize();"))
        self.assertIn('new Intl.DateTimeFormat(localeForLanguage()', script)
        self.assertLess(html.index('id="series_member"'), html.index('id="tag"'))
        self.assertLess(html.index('id="tag"'), html.index('id="media_type"'))
        self.assertNotIn('data-i18n="filters"', html)
        self.assertIn('class="title-filter-heading"', html)
        self.assertIn('data-i18n="resetAll"', html)
        self.assertIn('resetAll: "重置全部"', script)
        self.assertIn('custom: "自定义"', script)
        self.assertLess(html.index('data-i18n="titleAlias"'), html.index('id="reset"'))
        self.assertIn("function eraDateRange", script)
        self.assertIn("function applyEraDateRange", script)
        self.assertIn("function syncEraSeasonFromDates", script)
        self.assertIn('<span data-i18n="era">年</span', html)
        self.assertIn('<span data-i18n="season">季</span', html)
        self.assertIn('if (season === "winter") return { from: `${y - 1}-12`, to: `${y}-02` };', script)
        self.assertIn('if (season === "spring") return { from: `${y}-03`, to: `${y}-05` };', script)
        self.assertIn('if (!matchedEra && fromParts.year === toParts.year)', script)
        self.assertIn('if (from) $("start_from").value = `${year}-${from.month}`;', script)
        self.assertIn('ensureEraYearOption(year);', script)
        self.assertIn('imagesPreparedThrough', script)
        self.assertIn('archiveBuildSummary', script)
        status_renderer = script.split("function renderScanProgress", 1)[1].split("let syncSummaryTimer", 1)[0]
        self.assertNotIn('estimatedRemaining', status_renderer)
        self.assertNotIn('estimatedTime', status_renderer)
        self.assertNotIn('currentItem', status_renderer)
        self.assertIn('return { from: `${y}-01`, to: `${y}-12` };', script)
        self.assertIn('to: `${first + 9}-12`', script)
        self.assertIn('$("era").value = matchedEra', script)
        self.assertIn(".relation-edge.relation-side_story path", styles)
        self.assertIn("stroke-dasharray: 6 4", styles)
        self.assertIn(".relation-edge.relation-spin_off path", styles)
        self.assertIn("stroke-dasharray: 11 4 2 4", styles)
        self.assertIn(".relation-edge.relation-prequel path", styles)
        self.assertIn(".relation-edge.relation-character_appearance path", styles)
        self.assertIn(".relation-edge.relation-collaboration path", styles)
        self.assertIn(".relation-edge.relation-other path", styles)
        self.assertIn("width: 34px", styles)
        self.assertIn("repeating-linear-gradient", styles)
        self.assertIn('id="submitStoppedPlan"', script)
        self.assertIn("confirmStopped: true", script)
        self.assertIn('data-plan-route="ani-rss"', script)
        self.assertIn('data-plan-route="torrent"', script)
        self.assertIn('data-plan-route="default"', script)
        self.assertIn('submitStopped: "确认提交"', script)
        self.assertIn('x.usable_torrent_count > 0 || x.ani_rss_resource_count > 0 || x.ani_rss_search_available', script)
        self.assertNotIn('x.ani_rss_resource_count > 0 || x.ani_rss_auto_available', script)

    def test_cover_theme_anirss_delete_and_branding_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        boot = (STATIC / "boot.js").read_text(encoding="utf-8")
        self.assertIn('<p class="eyebrow" data-i18n="catalogTagline">全自动动画收藏库</p>', html)
        self.assertIn('<h1 data-i18n="catalog">AnimeMachine</h1>', html)
        self.assertNotIn("AnimeMachine·Automated Anime Library", html + script)
        self.assertIn('id="themeToggle"', html)
        self.assertIn('localStorage.getItem("anm-theme")', boot)
        self.assertIn('html[data-theme="dark"]', styles)
        self.assertIn('html[data-theme="dark"] .card:not(.with-cover)', styles)
        self.assertIn('html[data-theme="dark"] .badge.library', styles)
        self.assertEqual(1, script.count('data-cover-reload="${x.id}"'))
        self.assertIn('class="badge ${x.ani_rss_managed ? "ani-rss-managed" : "ani-rss-resource"}', script)
        self.assertIn('"ani-rss-managed"', script)
        self.assertIn('value="torrent"', html)
        self.assertIn('value="ani-rss"', html)
        self.assertIn('"ani-rss-resource"', script)
        self.assertIn('/api/ani-rss/subscriptions/${encodeURIComponent(button.dataset.aniRssDelete)}/delete', script)
        self.assertIn('data-ani-rss-delete', script)
        self.assertNotIn('torrent-exclusion">| ', script)
        self.assertIn('padding-right: 2ch', styles)
        self.assertIn('github.com/kyupi-git/animemachine', html)
        self.assertIn('cover.offsetTop + cover.offsetHeight', script)

    def test_bulk_plan_click_never_passes_pointer_event_as_routing_mode(self):
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        self.assertIn('$("createPlan").onclick = () => createPlan();', script)
        self.assertNotIn('$("createPlan").onclick = createPlan;', script)
        self.assertIn('typeof routingMode !== "string"', script)
        self.assertIn('invalidDownloadRoute: "下载方式无效，请刷新页面后重新选择作品。"', script)


    def test_cross_year_season_and_safe_settings_persistence_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        season_block = html[html.index('id="season"'):html.index('</select>', html.index('id="season"'))]
        self.assertLess(season_block.index('value="winter"'), season_block.index('value="spring"'))
        self.assertLess(season_block.index('value="spring"'), season_block.index('value="summer"'))
        self.assertLess(season_block.index('value="summer"'), season_block.index('value="autumn"'))
        for label in ("冬（1月前后）", "春（4月前后）", "夏（7月前后）", "秋（10月前后）"):
            self.assertIn(label, html)
        self.assertIn('if (season === "winter") return { from: `${y - 1}-12`, to: `${y}-02` }', script)
        self.assertIn('if (season === "spring") return { from: `${y}-03`, to: `${y}-05` }', script)
        self.assertIn('if (season === "summer") return { from: `${y}-06`, to: `${y}-08` }', script)
        self.assertIn('if (season === "autumn") return { from: `${y}-09`, to: `${y}-11` }', script)
        self.assertIn('const candidateYears = [...new Set([fromParts.year, toParts.year, fromParts.year + 1])]', script)
        self.assertIn('storedSeasonYear = storedTo.year', script)
        self.assertIn('storedRange.reversible === false', script)
        self.assertIn('$("era").value = storedEra', script)
        self.assertNotIn("仅当前进程", html)
        self.assertNotIn("重启后失效", html)

        start = script.index("async function saveSettings(e) {")
        end = script.index("\nfunction archiveText(s) {", start)
        save = script[start:end]
        self.assertIn("const nextConfig = JSON.parse(JSON.stringify(config))", save)
        self.assertNotIn("config.", save)
        self.assertLess(save.index('throw new Error(t("directPathMappings"))'), save.index('api("/api/settings"'))
        self.assertLess(save.index('throw new Error(t("metadataEndpointsRequired"))'), save.index('api("/api/settings"'))
        self.assertIn('JSON.stringify({ config: nextConfig, credentials })', save)
        self.assertNotIn('api("/api/config"', save)
        self.assertNotIn("configureAniRssCredential", save)
        self.assertNotIn("configureQbtCredential", save)
        self.assertIn("config = nextConfig", save)

        test_connection = script[script.index("async function testConnection(kind) {"):script.index("async function loadLogs()", script.index("async function testConnection(kind) {"))]
        self.assertIn("apiKey = $(isAniRss ? \"aniRssApiKey\" : \"qbtApiKey\").value.trim()", test_connection)
        self.assertIn("JSON.stringify({ kind, endpoint, apiKey })", test_connection)
        self.assertNotIn("configureAniRssCredential", test_connection)
        self.assertNotIn("configureQbtCredential", test_connection)


    def test_settings_transaction_and_manual_recovery_contract(self):
        source = (PROJECT / "src" / "animemachine" / "catalog" / "service.py").read_text(encoding="utf-8")
        settings = source[source.index('if parsed.path == "/api/settings":'):source.index('if parsed.path == "/api/connections/test":')]
        self.assertIn("with SETTINGS_WRITE_LOCK:", settings)
        self.assertLess(settings.index("config_store.validate_for_write(draft)"), settings.index("config_store.write(draft)"))
        self.assertLess(settings.index("config_store.write(draft)"), settings.index("credential_store.store_many(values, STATE_DIR)"))
        self.assertIn("if had_persistent_config:", settings)
        self.assertIn("config_store.write(previous)", settings)
        self.assertIn('"saved": True, "config": draft', settings)
        self.assertIn("invalidate_health_cache()", settings)
        probe = source[source.index('if parsed.path == "/api/connections/test":'):source.index('if parsed.path == "/api/connections/qbittorrent/credential":')]
        self.assertIn("with network_connectivity.recovery_probe():", probe)
        subtitle = source[source.index('if parsed.path == "/api/connections/subtitles/credentials":'):source.index('if parsed.path == "/api/library/audit":')]
        self.assertIn("with SETTINGS_WRITE_LOCK:", subtitle)
        self.assertIn("credential_store.store_many(values, STATE_DIR)", subtitle)
        self.assertIn("invalidate_health_cache()", subtitle)

        script = (STATIC / "app.js").read_text(encoding="utf-8")
        save = script[script.index("async function saveSettings(e) {"):script.index("\nfunction archiveText(s) {", script.index("async function saveSettings(e) {"))]
        self.assertIn("loadSystemHealth();", save)
        month = script[script.index("function localizedMonth(value) {"):script.index("function diagnosticRouteLabel", script.index("function localizedMonth(value) {"))]
        self.assertIn('if (year < 1 || month < 1 || month > 12) return "—";', month)
        self.assertIn("date.setUTCFullYear(year, month - 1, 1);", month)
        self.assertIn('const frontierLabel = language.startsWith("zh") ? frontier : localizedMonth(frontier);', script)
        self.assertIn('frontier && frontierLabel !== "—"', script)



if __name__ == "__main__":
    unittest.main()
