import unittest
from pathlib import Path

from animemachine.catalog.service import requires_admin


ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parents[1]
STATIC = PROJECT / "src" / "animemachine" / "web" / "static"


class WebContractTests(unittest.TestCase):

    def test_capability_policy_blocks_admin_side_effects_before_execution(self):
        for path in (
            "/api/catalog/reshuffle", "/api/archive/update", "/api/archive/import",
            "/api/metadata/repair", "/api/library/audit", "/api/history/1/restore",
            "/api/auth/users", "/api/auth/users/7",
        ):
            self.assertTrue(requires_admin("POST", path), path)
        for method, path in (("PUT", "/api/config"), ("GET", "/api/logs"), ("GET", "/api/history"), ("GET", "/api/auth/users")):
            self.assertTrue(requires_admin(method, path), path)
        for path in ("/api/anime", "/api/anime/1/image/refresh", "/api/plans/" + "a" * 32 + "/submit"):
            self.assertFalse(requires_admin("POST", path), path)

    def test_release_https_and_offline_archive_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        dockerfile = (PROJECT / "packaging" / "docker" / "Dockerfile").read_text(encoding="utf-8")
        release = (PROJECT / "scripts" / "windows" / "Build-Release.ps1").read_text(encoding="utf-8")
        self.assertNotIn("Path]::GetRelativePath", release)
        tls = (PROJECT / "src" / "animemachine" / "network" / "tls.py").read_text(encoding="utf-8")
        requirements = (PROJECT / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn('id="importArchive"', html)
        self.assertIn('id="archiveFile"', html)
        self.assertIn('/api/archive/import', script)
        self.assertIn('certifi==', requirements)
        self.assertIn('truststore==', requirements)
        self.assertIn('pip install', release)
        self.assertIn('ca-certificates', dockerfile)
        self.assertIn('ANM_CA_BUNDLE', tls)
        self.assertNotIn("player bridge", script.casefold())

    def test_auth_filter_memory_grouped_sources_and_playback_selection(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        for element_id in ("loginDialog", "loginForm", "authButton", "submissionAllowed", "userList"):
            self.assertIn(f'id="{element_id}"', html)
        self.assertIn('data-admin-only', html)
        self.assertIn('const filterStorageKey = "anm-catalog-filters-v1"', script)
        self.assertIn("function restoreFilterState()", script)
        self.assertIn("torrentGroups = (rows)", script)
        self.assertIn("sequence.isdisjoint", (PROJECT / "src" / "animemachine" / "torrents" / "runtime.py").read_text(encoding="utf-8"))
        self.assertIn('playbackSources.get(animeId)', script)
        self.assertIn("Continue with the selection-based fallback", script)
        self.assertNotIn("Player-Bridge", script)
        self.assertIn('class="log-item user-row"', script)
        self.assertIn('function playbackHtml(state, localMediaAvailable = false)', script)
        self.assertIn('&& !localMediaAvailable && !capabilities.qbtCredentialConfigured', script)
        self.assertIn('playbackHtml(playbackState, playableTargets.length > 0)', script)
        self.assertNotIn('data-i18n="acceptedContentHint"', html)

    def test_settings_and_filters_are_product_features(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        for element_id in ("archiveGroups", "serialGroupsZh", "serialGroupsEn", "serialGroupsJa",
                           "serialSubtitleLanguage", "otherGroupsEnabled", "allowedResolutions", "torrentPoolPath",
                           "qbtEndpoint", "logList", "watchList", "directorSuggestions", "voiceSuggestions",
                           "relationDialog", "relationGraph", "series_member"):
            self.assertIn(f'id="{element_id}"', html)
        for element_id in ("repairMetadata", "externalReadOnlyEnabled", "externalReadOnlyKind", "externalReadOnlyPath"):
            self.assertIn(f'id="{element_id}"', html)
        self.assertNotIn("prowlarrEndpoint", html)
        self.assertNotIn("testProwlarr", script)
        self.assertIn('data-tab="groups"', html)
        self.assertIn('data-tab="priority"', html)
        self.assertNotIn('id="priorityColumns"', html)
        self.assertIn('class="priority-tree"', html)
        self.assertIn('["\u6807\u6e05", "Standard definition", "\u6a19\u6e96\u753b\u8cea"]', script)
        self.assertIn('api("/api/resource-groups",', script)
        self.assertIn("const archiveIds = new Set(p.archiveGroupIds", script)
        self.assertIn("p.resourceGroups.filter((x) => archiveIds.has(x.id))", script)
        self.assertNotIn("serialCatalog.flatMap", script)
        self.assertNotIn('<section class="about-product" aria-labelledby="aboutTitle">', html)
        self.assertNotIn("ABOUT ANIMEMACHINE", html)
        self.assertLess(html.index('data-tab="logs"'), html.index('data-tab="about"'))
        self.assertIn('catalog: "AnimeMachine"', script)
        self.assertIn('aboutTitle: "About AnimeMachine"', script)
        self.assertNotIn('catalog: "全自動アニメライブラリ"', script)
        self.assertNotIn("真实关联本地资源池与收藏库状态的全量动画数据库", script)
        self.assertNotIn("离线归档构建，可追溯、可筛选、可持续更新。", html)
        self.assertIn('src="/boot.js"', html)
        boot = (STATIC / "boot.js").read_text(encoding="utf-8")
        self.assertIn("navigator.languages || [navigator.language]", boot)
        self.assertIn('const saved = localStorage.getItem("anm-language")', boot)
        self.assertIn("if (supported.has(saved)) language = saved", boot)
        self.assertIn("detectSystemLanguage", script)
        self.assertIn("storedLanguage() || detectSystemLanguage(c.ui?.availableLanguages)", script)
        self.assertIn('data-i18n="loadingWorks"', html)
        self.assertIn('loadingWorks: "Loading works, please wait..."', script)
        self.assertNotIn("制作 ·", script)
        self.assertLess(html.index('id="country"'), html.index('id="studio"'))
        self.assertLess(html.index('id="studio"'), html.index('id="media_type"'))
        self.assertIn('config.ui?.filterDefaults?.country || "JP"', script)
        self.assertIn('["__other__", allow.resolution !== false]', script)
        self.assertIn('movie: ["剧场版 / 电影", "Theatrical / film", "劇場版 / 映画"]', script)
        self.assertIn('light_novel: ["轻小说改"', script)
        self.assertIn('novel: ["小说改"', script)
        self.assertIn('time_travel: ["穿越", "Time travel", "タイムトラベル"]', script)
        self.assertIn('galgame: ["Galgame", "Galgame", "美少女ゲーム"]', script)
        self.assertIn('yuri: ["百合", "Yuri", "百合"]', script)
        self.assertIn('magical_girl: ["魔法少女", "Magical girl", "魔法少女"]', script)
        self.assertIn('harem: ["后宫", "Harem", "ハーレム"]', script)
        self.assertIn('children: ["儿童向", "Children", "子供向け"]', script)
        self.assertIn('avant_garde: ["非常规表达", "Unconventional expression", "非定型表現"]', script)
        self.assertNotIn('shounen: [', script)
        self.assertNotIn('seinen: [', script)
        self.assertNotIn('shoujo: [', script)
        self.assertNotIn('drama: [', script)
        self.assertIn('same_setting: ["", "", ""]', script)
        self.assertIn('sameAsOriginalLanguage(x)', script)
        self.assertIn('Number(catalogStats.runtime?.torrents || 0) === 0', script)
        self.assertIn('id="scanProgress"', html)
        self.assertIn('searchPoolNow: "重新搜索本地资源"', script)
        self.assertIn('searchAniRss: "通过 Ani-RSS 查询资源"', script)
        self.assertIn('id="aniRssMode"', html)
        self.assertIn('verifyWork: "立即核验"', script)
        self.assertNotIn('id="minimumDate"', html)
        self.assertNotIn('id="refreshImage"', script)
        self.assertIn('availability: "可用来源"', script)
        self.assertIn('externalMediaAvailable: "外部媒体已映射"', script)
        self.assertIn('external: "外部来源（只读）"', script)
        self.assertIn('sourceType: "类型"', script)
        self.assertIn('originalName: "原作名称"', script)
        self.assertIn('originalAuthor: "作者"', script)
        self.assertIn('seriesComposition: "系列构成"', script)
        self.assertIn('characterDesign: "角色设计"', script)
        self.assertIn('music: "音乐"', script)
        self.assertIn('excludedSerialProfile: "语言不符"', script)
        self.assertIn('excludedResolution: "分辨率不符"', script)
        self.assertIn('factHtml("original-name-fact"', script)
        self.assertIn('factHtml("tags-fact"', script)
        self.assertIn('label("theme", code)', script)
        self.assertIn('storageDirectories = [...new Set(group.members.map((item) => item.storageDirectory)', script)
        self.assertNotIn('${esc(group.sample.name)}', script)
        self.assertIn('<b>Ani-RSS</b>', script)
        self.assertIn('resourceResolutionText = (value, scan = "p")', script)
        self.assertIn('["unknown", "other", "null", "0"].includes(lower)', script)
        self.assertIn('resourceResolutionText(y.resolution, y.scan)', script)
        self.assertIn('resourceResolutionText(y.resolution)', script)
        self.assertIn('stateOther: "状态待确认"', script)
        self.assertNotIn('unavailable: "暂无资源"', script)
        self.assertIn('x.has_external_media', script)
        self.assertIn('class="completion unassessed"', script)
        self.assertIn('originalWithKind: "原作·{kind}"', script)
        self.assertIn('adaptationWithKind: "改编·{kind}"', script)
        self.assertIn('id="relationSubjectPopover"', html)
        self.assertIn("function relationSubjectChips(node)", script)
        self.assertIn("function showRelationSubjectPopover", script)
        self.assertIn("return node.title_ja || preferred(node)", script)
        self.assertIn("function relationMonth(v)", script)
        self.assertIn('month: "short"', script)
        self.assertIn('graph.seriesTitle || graphTitle', script)
        self.assertIn('class="relation-node-foot"', script)
        self.assertIn(".relation-subject-popover", (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn('y.relation_code !== "other"', script)
        self.assertIn('href="https://bgm.tv/subject/${Number(y.related_bgm_id)}"', script)
        self.assertIn('id="detailRelations"', script)
        self.assertIn("localizedSummary(x)", script)
        self.assertIn('t("externalSource")} · ${t("readOnlyMapping")}', script)
        unavailable = html.index('value="unavailable"')
        self.assertNotIn("checked", html[unavailable:unavailable + 80])
        self.assertIn("showRelationGraph", script)
        self.assertIn('id="reshuffle"', html)
        self.assertIn('relationDialog.classList.toggle("expanded")', script)
        self.assertIn('relatedWorksCount: "系列内作品数：{count}"', script)
        self.assertIn('data-relation-toggle=', script)
        self.assertIn('data-relation-export="png"', script)
        self.assertIn('data-relation-export="svg"', script)
        self.assertIn("global_search_only", script)
        self.assertIn("layoutRelationLabels", script)
        self.assertIn("relationGraphBounds", script)
        self.assertIn("safePadding = 28", script)
        self.assertIn('transform="translate(${shiftX} ${shiftY})"', script)
        self.assertIn("labelOverlap * 2000", script)
        self.assertIn("relationTrackCodes", script)
        self.assertIn("routeRelationEdge", script)
        self.assertIn('sequel: { offset: 0, side: 0 }', script)
        self.assertIn("if (!obstacle && sourceY === targetY", script)
        self.assertIn("assignRelationPorts", script)
        self.assertIn("centerPortPriority", script)
        self.assertIn('edge.relation_code === "sequel" && chronologyCorrect', script)
        self.assertIn("Number(!sameRow) * 10 + relationRank", script)
        self.assertIn("relationLaneCapacity", script)
        self.assertIn("route.local", script)
        self.assertIn("routedRelationMetadata", script)
        self.assertIn("routedTotal - routedLane - 1", script)
        self.assertIn("corridorRank * corridorLaneSpacing", script)
        self.assertNotIn("`outer:${style.side}:${edge.target_anime_id}`", script)
        self.assertIn("assignRelationPorts(orderedEdges, positions, nodesById)", script)
        self.assertIn("distribute(negative, -38, 0, 0)", script)
        self.assertIn("verticalCorridorClear", script)
        self.assertIn("Math.abs(sourceCenterX - targetCenterX) <= 24", script)
        self.assertIn("verticalGapBottom - verticalGapTop >= 12", script)
        self.assertIn("direct: !collisionNudge,\n      vertical: true", script)
        self.assertIn("route.direct && !route.vertical", script)
        self.assertIn('prequel: ["前传", "Prequel", "前日譚"]', script)
        self.assertIn('prequel: { offset: 0, side: 0 }', script)
        self.assertIn("verticalGroups", script)
        self.assertIn("laneXSpacing", script)
        self.assertIn("laneYSpacing", script)
        self.assertIn("corridorLaneSpacing", script)
        self.assertIn("targetId: edge.target_anime_id", script)
        self.assertIn("other.targetId === item.targetId", script)
        self.assertIn("other.horizontals.some", script)
        self.assertIn("relationSegmentConflictCost", script)
        self.assertIn("createRelationSegmentIndex", script)
        self.assertIn("cellSize = 96", script)
        self.assertIn("segmentIndex.conflictScore", script)
        self.assertIn("collisionNudge", script)
        self.assertIn("baseCenteredLane", script)
        self.assertIn("candidateCenteredLane", script)
        self.assertIn('data-source="${edge.source_anime_id}"', script)
        self.assertIn('data-target="${edge.target_anime_id}"', script)
        self.assertIn("refineRelationRouting", script)
        self.assertIn("!verticalCorridorClear", script)
        self.assertIn("preferredSide", script)
        self.assertIn("bypass: true", script)
        self.assertIn("Number(right.bypass) - Number(left.bypass)", script)
        self.assertIn("const center = (group.length - 1) / 2", script)
        self.assertIn("const outerGroups = []", script)
        self.assertIn("other.side === item.side", script)
        self.assertIn("outerGroups.forEach", script)
        self.assertIn("String(aTarget?.start_month).localeCompare", script)
        self.assertIn("sourceTurnRank", script)
        self.assertIn("sourceTurnTotal - sourceTurnRank - 1", script)
        self.assertIn("sourceFans", script)
        self.assertIn("routeObstacleCount", script)
        self.assertIn("!edge.grouping && (sourceAbove || sourceBelow)", script)
        self.assertIn("contextRoute: true", script)
        self.assertIn("diagonal: true", script)
        self.assertIn("route.targetSegment", script)
        self.assertIn("contextGroups", script)
        self.assertIn("Gray cross-series connectors", script)
        self.assertIn("relationPathSegments", script)
        self.assertIn("foreignLineOverlap", script)
        self.assertIn("灰色的虚框节点是相关联的不同系列作品", script)
        self.assertIn("Gray dashed nodes are related works from other series", script)
        self.assertIn("灰色の破線枠ノードは、関連する別シリーズの作品です", script)
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        self.assertIn("height: min(780px, 88vh)", styles)
        self.assertIn("scrollbar-gutter: stable both-edges", styles)
        self.assertIn("protectedTargets.has(edge.target_anime_id)", script)
        self.assertIn(".relation-edge-label", (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn('not_in_library_catalog: "未加入本地库"', script)
        self.assertIn('graphUnavailableSelect: "当前没有可提交的合格资源"', script)
        self.assertIn("canSelect = node.selectable", script)
        self.assertIn('canSelect ? "" : "disabled"', script)
        self.assertNotIn("relation-node-dot", script)
        self.assertIn("terminalLead = 34 + routedLane * 8", script)
        self.assertIn("contextGap =", script)
        self.assertIn('background-position: center 33%', (STATIC / "styles.css").read_text(encoding="utf-8"))
        self.assertIn("stage_replace", script)
        self.assertIn("graphExistingWarning", script)
        self.assertIn('pageSize = "12"', script)
        self.assertIn('<option value="20">20</option>', html)
        self.assertIn('seriesWork: "系列作品"', script)
        self.assertIn('seriesWork: "Series work"', script)
        self.assertIn('seriesWork: "シリーズ作品"', script)
        self.assertIn("coverObserver?.disconnect()", script)
        self.assertIn("batch.active < 12", script)
        self.assertIn("searchController?.abort()", script)
        self.assertIn("cancelCoverLoads();", script)
        self.assertIn('{ rootMargin: "900px" }', script)
        self.assertIn("sameMediaMainlineLinks", script)
        self.assertIn("explicitGraphSequenceNumber", script)
        self.assertIn("relaxCrossingBranchTargets", script)
        self.assertIn("candidates = [28, -28, 56, -56]", script)
        self.assertIn("detour * 1.6", script)
        self.assertIn("mediaOrder.length + index", script)
        self.assertNotIn("personHint", script)
        self.assertNotIn('data-i18n="personHint"', html)
        self.assertIn("margin: 18px auto 60px", styles)
        self.assertIn('searchPlaceholder: "中文、英文、日语或简称"', script)
        self.assertIn('searchPlaceholder: "English, Japanese, Chinese or abbreviation"', script)
        self.assertIn('searchPlaceholder: "日本語・英語・中国語・略称"', script)
        self.assertIn("endMonth - 1 - 5", script)
        self.assertIn('$("start_to").value = monthValue(endYear, endMonth)', script)
        self.assertIn("function localizeStaticUi()", script)
        self.assertLess(script.rindex("localizeStaticUi();"), script.rindex("initialize();"))
        self.assertIn('new Intl.DateTimeFormat(localeForLanguage()', script)
        self.assertLess(html.index('id="series_member"'), html.index('id="tag"'))
        self.assertLess(html.index('id="tag"'), html.index('id="media_type"'))
        self.assertNotIn('data-i18n="filters"', html)
        self.assertIn('class="title-filter-heading"', html)
        self.assertIn('data-i18n="resetAll"', html)
        self.assertIn('resetAll: "重置全部"', script)
        self.assertIn('custom: "自定义"', script)
        self.assertLess(html.index('data-i18n="titleAlias"'), html.index('id="reset"'))
        self.assertIn("function eraDateRange", script)
        self.assertIn("function applyEraDateRange", script)
        self.assertIn("function syncEraFromDates", script)
        self.assertIn('from: `${value}-01`, to: `${value}-12`', script)
        self.assertIn('to: `${first + 9}-12`', script)
        self.assertIn('$("era").value = matching || ""', script)
        self.assertIn('String(a).toLowerCase() === "other"', script)
        self.assertIn("Number(aOther) - Number(bOther)", script)
        self.assertIn(".relation-edge.relation-side_story path", styles)
        self.assertIn("stroke-dasharray: 6 4", styles)
        self.assertIn(".relation-edge.relation-spin_off path", styles)
        self.assertIn("stroke-dasharray: 11 4 2 4", styles)
        self.assertIn(".relation-edge.relation-prequel path", styles)
        self.assertIn(".relation-edge.relation-character_appearance path", styles)
        self.assertIn(".relation-edge.relation-collaboration path", styles)
        self.assertIn(".relation-edge.relation-other path", styles)
        self.assertIn("width: 34px", styles)
        self.assertIn("repeating-linear-gradient", styles)
        self.assertIn('id="submitStoppedPlan"', script)
        self.assertIn("confirmStopped: true", script)
        self.assertIn('data-plan-route="ani-rss"', script)
        self.assertIn('data-plan-route="torrent"', script)
        self.assertIn('data-plan-route="default"', script)
        self.assertIn('submitStopped: "确认提交"', script)
        self.assertIn('x.usable_torrent_count > 0 || x.ani_rss_resource_count > 0', script)
        self.assertNotIn('x.ani_rss_resource_count > 0 || x.ani_rss_auto_available', script)

    def test_cover_theme_anirss_delete_and_branding_contract(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        styles = (STATIC / "styles.css").read_text(encoding="utf-8")
        boot = (STATIC / "boot.js").read_text(encoding="utf-8")
        self.assertIn('<p class="eyebrow">Automated Anime Library</p>', html)
        self.assertIn('<h1 data-i18n="catalog">AnimeMachine</h1>', html)
        self.assertNotIn("AnimeMachine·Automated Anime Library", html + script)
        self.assertIn('id="themeToggle"', html)
        self.assertIn('localStorage.getItem("anm-theme")', boot)
        self.assertIn('html[data-theme="dark"]', styles)
        self.assertIn('html[data-theme="dark"] .card:not(.with-cover)', styles)
        self.assertIn('html[data-theme="dark"] .badge.library', styles)
        self.assertEqual(1, script.count('data-cover-reload="${x.id}"'))
        self.assertIn('class="badge ${kind}"', script)
        self.assertIn('"ani-rss-managed"', script)
        self.assertIn('"ani-rss-resource"', script)
        self.assertIn('/api/ani-rss/subscriptions/${encodeURIComponent(button.dataset.aniRssDelete)}/delete', script)
        self.assertIn('data-ani-rss-delete', script)
        self.assertNotIn('torrent-exclusion">| ', script)
        self.assertIn('padding-right: 2ch', styles)
        self.assertIn('github.com/kyupi-git/animemachine', html)
        self.assertIn('cover.offsetTop + cover.offsetHeight', script)

    def test_bulk_plan_click_never_passes_pointer_event_as_routing_mode(self):
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        self.assertIn('$("createPlan").onclick = () => createPlan();', script)
        self.assertNotIn('$("createPlan").onclick = createPlan;', script)
        self.assertIn('typeof routingMode !== "string"', script)
        self.assertIn('invalidDownloadRoute: "下载方式无效，请刷新页面后重新选择作品。"', script)


if __name__ == "__main__":
    unittest.main()
